// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuxf3LEXZGIIxmNe-yXRTtzxlnSHCBJYQ',
    appId: '1:441646831902:web:a19c64a5c33886fe85d10f',
    messagingSenderId: '441646831902',
    projectId: 'chat-app-89871',
    authDomain: 'chat-app-89871.firebaseapp.com',
    storageBucket: 'chat-app-89871.firebasestorage.app',
    measurementId: 'G-EE8FRMH8BE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjFn4Pxkz4kORcN0cH9AWBOZW6-k7x-Ig',
    appId: '1:441646831902:android:5d084b1ffa7cbad785d10f',
    messagingSenderId: '441646831902',
    projectId: 'chat-app-89871',
    storageBucket: 'chat-app-89871.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx9eK0TsmxHSNRsREjeP9GZVNE3dRvwHM',
    appId: '1:441646831902:ios:aa6232ed45b9487b85d10f',
    messagingSenderId: '441646831902',
    projectId: 'chat-app-89871',
    storageBucket: 'chat-app-89871.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx9eK0TsmxHSNRsREjeP9GZVNE3dRvwHM',
    appId: '1:441646831902:ios:aa6232ed45b9487b85d10f',
    messagingSenderId: '441646831902',
    projectId: 'chat-app-89871',
    storageBucket: 'chat-app-89871.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuxf3LEXZGIIxmNe-yXRTtzxlnSHCBJYQ',
    appId: '1:441646831902:web:4f6a808c3ea541de85d10f',
    messagingSenderId: '441646831902',
    projectId: 'chat-app-89871',
    authDomain: 'chat-app-89871.firebaseapp.com',
    storageBucket: 'chat-app-89871.firebasestorage.app',
    measurementId: 'G-RX2XHP8W4S',
  );
}
